/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.SisBanco.view;

import br.com.SisBanco.accessories.ApModeloGrade;
import br.com.SisBanco.beans.Agencia;
import br.com.SisBanco.beans.Cliente;
import br.com.SisBanco.dao.AgenciaDAO;
import br.com.SisBanco.dao.ClienteDAO;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import javax.swing.JComboBox;
import javax.swing.JInternalFrame;
import static javax.swing.JOptionPane.*;
import javax.swing.JTable;
import javax.swing.event.ChangeListener;
import javax.swing.text.JTextComponent;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Vinicius
 */
public class IFCliente extends JInternalFrame implements ChangeListener{        
      
    public IFCliente() {       
        initComponents(); 
        atualizarGrade();             
    }              

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpAbas = new javax.swing.JTabbedPane();
        spDados = new javax.swing.JScrollPane();
        tbDados = new javax.swing.JTable();
        pnCadastro = new javax.swing.JPanel();
        jlCpf = new javax.swing.JLabel();
        try{
            MaskFormatter fmtCpf = new MaskFormatter("###.###.###-##");
            fmtCpf.setPlaceholderCharacter('_');
            ftCpf = new javax.swing.JFormattedTextField(fmtCpf);
            jlNome = new javax.swing.JLabel();
            tfNome = new javax.swing.JTextField();
            jlAgencia = new javax.swing.JLabel();
            coAgencia = new javax.swing.JComboBox<Agencia>();
            btSalvar = new javax.swing.JButton();
            btAlterar = new javax.swing.JButton();
            btExcluir = new javax.swing.JButton();

            setClosable(true);
            setForeground(new java.awt.Color(0, 0, 0));
            setIconifiable(true);
            setMaximizable(true);
            setResizable(true);
            setTitle("Cadastro de Clientes");
            setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

            tpAbas.addChangeListener(this);

            tbDados.addMouseListener(new MouseHandler());
            tbDados.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {

                }
            ));
            tbDados.setToolTipText("Clique para Selecionar");
            tbDados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            tbDados.setFocusable(false);
            tbDados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
            spDados.setViewportView(tbDados);

            tpAbas.addTab("Seleção", spDados);

            jlCpf.setText(" CPF:");

        }catch(Exception ex){}

        jlNome.setText(" Nome:");

        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        jlAgencia.setText(" Agência:");

        try{
            coAgencia.setModel(new javax.swing.DefaultComboBoxModel<Agencia>(new AgenciaDAO().carregarCombo()));
            coAgencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        }catch(Exception ex){}
        coAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coAgenciaActionPerformed(evt);
            }
        });

        btSalvar.setBackground(new java.awt.Color(51, 153, 255));
        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(255, 255, 0));
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SisBanco/Salvar.png"))); // NOI18N
        btSalvar.setMnemonic('S');
        btSalvar.setText("  Salvar");
        btSalvar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        btSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btSalvarKeyReleased(evt);
            }
        });

        btAlterar.setBackground(new java.awt.Color(51, 153, 255));
        btAlterar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btAlterar.setForeground(new java.awt.Color(255, 255, 0));
        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SisBanco/Alterar.png"))); // NOI18N
        btAlterar.setMnemonic('A');
        btAlterar.setText("Alterar");
        btAlterar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btExcluir.setBackground(new java.awt.Color(51, 153, 255));
        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btExcluir.setForeground(new java.awt.Color(255, 51, 51));
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SisBanco/Excluir.png"))); // NOI18N
        btExcluir.setMnemonic('E');
        btExcluir.setText("Excluir");
        btExcluir.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCadastroLayout = new javax.swing.GroupLayout(pnCadastro);
        pnCadastro.setLayout(pnCadastroLayout);
        pnCadastroLayout.setHorizontalGroup(
            pnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadastroLayout.createSequentialGroup()
                .addGroup(pnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCadastroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ftCpf)
                            .addComponent(jlCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlNome, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(tfNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(coAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnCadastroLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnCadastroLayout.setVerticalGroup(
            pnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNome)
                    .addComponent(jlAgencia))
                .addGap(0, 0, 0)
                .addGroup(pnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addGroup(pnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        tpAbas.addTab("Cadastro", pnCadastro);
        pnCadastro.getAccessibleContext().setAccessibleParent(tpAbas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpAbas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpAbas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected  void atualizarGrade(){
        try {
            ResultSet rs = new ClienteDAO().carregarGrade();
            tbDados.setModel(new ApModeloGrade(rs,new String[]{"CPF", "Nome", "Agência"}));
            tbDados.getColumnModel().getColumn(0).setMaxWidth(100);
            tbDados.getColumnModel().getColumn(1).setMaxWidth(400);
            tbDados.getColumnModel().getColumn(2).setMaxWidth(100);
        } catch (Exception e) {
            showMessageDialog(this, e.getMessage(),"Erro",ERROR_MESSAGE);
        }
    }    
    
    class MouseHandler extends MouseAdapter {

        public void mouseReleased(MouseEvent e) {
            if (e.getButton() != MouseEvent.BUTTON1) {
                return;
            }
            JTable tb = (JTable) e.getSource();
            int lin = tb.getSelectionModel().getMinSelectionIndex();
            String codigo = tb.getModel().getValueAt(lin, 0).toString();

            try {
                carregarRegistro(codigo);
                tpAbas.setSelectedComponent(pnCadastro);
                tfNome.requestFocus();
            } catch (Exception ex) {
                showMessageDialog(IFCliente.this, ex.getMessage(), "Erro", ERROR_MESSAGE);
            }
        }
    }
    
    protected void incluir(){        
        Cliente c = new Cliente();
        c.setCpf(ftCpf.getText());
        c.setNome(tfNome.getText());
        Agencia agencia = (Agencia) coAgencia.getSelectedItem();
        c.setAgencia(agencia.getNumero());
        
        try {
            new ClienteDAO().cadastrarCliente(c);            
            atualizarGrade();
            tpAbas.setSelectedIndex(0);            
        } catch (Exception ex) {
            showMessageDialog(this,"Erro ao incluir cliente! " + ex.getMessage(),"Erro",ERROR_MESSAGE);
        }
        
    }    
    
    protected  void alterar(){
        Cliente c = new Cliente();
        c.setCpf(ftCpf.getText());
        c.setNome(tfNome.getText());
        Agencia agencia = (Agencia) coAgencia.getSelectedItem();
        c.setAgencia(agencia.getNumero());        
                
        try {
            new ClienteDAO().alterarCliente(c);
            atualizarGrade();
            tpAbas.setSelectedIndex(0);
        } catch (Exception ex) {
            showMessageDialog(this,ex.getMessage(),"Erro",ERROR_MESSAGE);
        }
    }
    
    protected void excluir(){
        try {
            new ClienteDAO().excluirCliente(ftCpf.getText());
            ApModeloGrade amg = (ApModeloGrade)tbDados.getModel();
            amg.removeRow(tbDados.getSelectedRow());
            tpAbas.setSelectedIndex(0);
        } catch (Exception ex) {
            showMessageDialog(this,ex.getMessage(),"Erro",ERROR_MESSAGE);
        }
    }
    
    protected void carregarRegistro(String codigo)throws Exception{
        Cliente c = new ClienteDAO().consultarCliente(codigo);
        ftCpf.setText(c.getCpf());
        tfNome.setText(c.getNome());
        coAgencia.setSelectedItem(c.getAgencia());             
    }    
    
    private void coAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coAgenciaActionPerformed

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == btSalvar) {                      
            incluir();         
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    
    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == btAlterar) {
            alterar();
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == btExcluir) {
            int opcao = showOptionDialog(this, "Tem certeza que deseja excluir esse cliente?", "Confirme", 0,
                QUESTION_MESSAGE, null, new String[]{"Sim", "Não"}, "Não");
            switch (opcao) {
                case -1:
                    return;
                case 0:
                    excluir();
                    break;                             
            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    public void stateChanged(javax.swing.event.ChangeEvent evt) {                                    
        // TODO add your handling code here:
        if (tpAbas.getSelectedIndex() != 0) {
            return;
        }
        for (int i = 0; i < pnCadastro.getComponentCount(); i++) {            
            if (pnCadastro.getComponent(i) instanceof JTextComponent) {                
                ((JTextComponent) pnCadastro.getComponent(i)).setText(""); 
            }            
            if (pnCadastro.getComponent(0) instanceof JComboBox) {                
                ((JComboBox) pnCadastro.getComponent(0)).setSelectedIndex(0);                
            }            
        }
    }     
    
    private void btSalvarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btSalvarKeyReleased
        // TODO add your handling code here:        
           if(evt.getKeyCode() == 10){               
               incluir();            
           }
    }//GEN-LAST:event_btSalvarKeyReleased

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox<Agencia> coAgencia;
    private javax.swing.JFormattedTextField ftCpf;
    private javax.swing.JLabel jlAgencia;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlNome;
    private javax.swing.JPanel pnCadastro;
    private javax.swing.JScrollPane spDados;
    private javax.swing.JTable tbDados;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTabbedPane tpAbas;
    // End of variables declaration//GEN-END:variables
}
