/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.SisBanco.view;

import br.com.SisBanco.beans.Conta;
import br.com.SisBanco.beans.ContaCorrente;
import br.com.SisBanco.dao.ContaDAO;
import java.text.ParseException;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.*;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Vinicius
 */
public class IFDeposito extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFDeposito
     */
    public IFDeposito() {
        initComponents();
    }
    
    protected void realizarDeposito(){
        try {
        Conta c = new ContaCorrente();  
        c.setDeposito(Double.parseDouble(ftValorDeposito.getText().replaceAll("\\,", ".")));         
        c.setNumeroConta(ftContaDeposito.getText());  
        c.setNumeroAgencia(ftAgenciaDeposito.getText());        
        
            new ContaDAO().depositar(c);           
        } catch (Exception ex) {
            showMessageDialog(this, "Erro ao efetuar depósito!" + ex.getMessage(),"Erro",ERROR_MESSAGE);
        }                
    }
    
    protected void limparCampos(){
        ftAgenciaDeposito.setText("");
        ftContaDeposito.setText("");
        ftValorDeposito.setText("");
        ftAgenciaDeposito.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlAgenciaDeposito = new javax.swing.JLabel();
        try {
            MaskFormatter fmtNumero = new MaskFormatter("####-#");
            fmtNumero.setPlaceholderCharacter('_');
            ftAgenciaDeposito = new javax.swing.JFormattedTextField(fmtNumero);
            jlContaDeposito = new javax.swing.JLabel();
            try{
                MaskFormatter fmtConta = new MaskFormatter("#####-##");
                fmtConta.setPlaceholderCharacter('_');
                ftContaDeposito = new javax.swing.JFormattedTextField(fmtConta);
                jlValorDeposito = new javax.swing.JLabel();
                ftValorDeposito = new javax.swing.JFormattedTextField(new Double(0));
                btConfirmar = new javax.swing.JButton();
                btLimpar = new javax.swing.JButton();

                setBackground(new java.awt.Color(51, 204, 255));
                setClosable(true);
                setIconifiable(true);
                setMaximizable(true);
                setTitle("Depósito");
                setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

                jlAgenciaDeposito.setText(" Agência:");

            }catch(ParseException pe){}

            jlContaDeposito.setText(" Conta:");

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "O erro é na conta para depósito", "Erro", 0);
        }

        jlValorDeposito.setText(" Valor:");

        ftValorDeposito.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        btConfirmar.setBackground(new java.awt.Color(204, 204, 204));
        btConfirmar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btConfirmar.setForeground(new java.awt.Color(0, 204, 51));
        btConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SisBanco/L_Ok.jpg"))); // NOI18N
        btConfirmar.setMnemonic('C');
        btConfirmar.setText("Confirmar");
        btConfirmar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btConfirmarMouseExited(evt);
            }
        });
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });
        btConfirmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btConfirmarKeyReleased(evt);
            }
        });

        btLimpar.setBackground(new java.awt.Color(204, 204, 204));
        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btLimpar.setForeground(new java.awt.Color(255, 51, 51));
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SisBanco/L_Limpar.png"))); // NOI18N
        btLimpar.setMnemonic('L');
        btLimpar.setText("Limpar");
        btLimpar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btLimpar.setPreferredSize(new java.awt.Dimension(93, 33));
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jlAgenciaDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(102, 102, 102)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ftContaDeposito)
                                .addComponent(ftAgenciaDeposito)
                                .addComponent(ftValorDeposito)
                                .addComponent(jlContaDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlValorDeposito, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jlAgenciaDeposito)
                .addGap(0, 0, 0)
                .addComponent(ftAgenciaDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlContaDeposito)
                .addGap(0, 0, 0)
                .addComponent(ftContaDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlValorDeposito)
                .addGap(0, 0, 0)
                .addComponent(ftValorDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        if(evt.getSource() == btConfirmar)
            realizarDeposito();
            this.dispose();
    }//GEN-LAST:event_btConfirmarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        if(evt.getSource() == btLimpar)
            limparCampos();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btConfirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btConfirmarMouseExited
        // TODO add your handling code here:       
    }//GEN-LAST:event_btConfirmarMouseExited

    private void btConfirmarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btConfirmarKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            realizarDeposito();
            this.dispose();
        }
    }//GEN-LAST:event_btConfirmarKeyReleased
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConfirmar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JFormattedTextField ftAgenciaDeposito;
    private javax.swing.JFormattedTextField ftContaDeposito;
    private javax.swing.JFormattedTextField ftValorDeposito;
    private javax.swing.JLabel jlAgenciaDeposito;
    private javax.swing.JLabel jlContaDeposito;
    private javax.swing.JLabel jlValorDeposito;
    // End of variables declaration//GEN-END:variables
}
