/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.SisBanco.view;

import br.com.SisBanco.beans.Conta;
import br.com.SisBanco.beans.ContaCorrente;
import br.com.SisBanco.dao.ContaDAO;
import java.text.ParseException;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.*;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Vinicius
 */
public class IFSaque extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form IFSaque
     */
    public IFSaque() {
        initComponents();
    }
    
    protected void realizarSaque(){
        try {
        Conta c = new ContaCorrente();                  
        c.setNumeroConta(ftContaSaque.getText());  
        c.setNumeroAgencia(ftAgenciaSaque.getText()); 
        c.setSaque(Double.parseDouble(ftValorSaque.getText().replaceAll("\\,", ".")));
        String senha = new String(pfSenhaSaque.getPassword()).trim();                
        c.setSenha(senha);
        
            new ContaDAO().sacar(c);           
        } catch (Exception ex) {
            showMessageDialog(this, "Erro ao efetuar saque!" + ex.getMessage(),"Erro",ERROR_MESSAGE);
        }                
    }
    
    protected void limparCampos(){
        ftAgenciaSaque.setText("");
        ftContaSaque.setText("");
        pfSenhaSaque.setText("");
        ftValorSaque.setText("");
        ftAgenciaSaque.requestFocus();
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlAgenciaSaque = new javax.swing.JLabel();
        try {
            MaskFormatter fmtNumero = new MaskFormatter("####-#");
            fmtNumero.setPlaceholderCharacter('_');
            ftAgenciaSaque = new javax.swing.JFormattedTextField(fmtNumero);
            jlContaSaque = new javax.swing.JLabel();
            try{
                MaskFormatter fmtConta = new MaskFormatter("#####-##");
                fmtConta.setPlaceholderCharacter('_');
                ftContaSaque = new javax.swing.JFormattedTextField(fmtConta);
                jlValorSaque = new javax.swing.JLabel();
                ftValorSaque = new javax.swing.JFormattedTextField(new Double(0));
                jlSenhaSaque = new javax.swing.JLabel();
                pfSenhaSaque = new javax.swing.JPasswordField();
                btConfirmar = new javax.swing.JButton();
                btLimpar = new javax.swing.JButton();

                setBackground(new java.awt.Color(51, 204, 255));
                setClosable(true);
                setIconifiable(true);
                setMaximizable(true);
                setTitle("Saque");
                setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

                jlAgenciaSaque.setText(" Conta:");

            }catch(ParseException pe){}
            ftAgenciaSaque.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ftAgenciaSaqueActionPerformed(evt);
                }
            });

            jlContaSaque.setText(" Valor:");

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "O erro é na conta para depósito", "Erro", 0);
        }
        ftContaSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftContaSaqueActionPerformed(evt);
            }
        });

        jlValorSaque.setText(" Senha:");

        ftValorSaque.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        ftValorSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftValorSaqueActionPerformed(evt);
            }
        });

        jlSenhaSaque.setText(" Agência:");

        pfSenhaSaque.setEchoChar('*');
        pfSenhaSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfSenhaSaqueActionPerformed(evt);
            }
        });

        btConfirmar.setBackground(new java.awt.Color(204, 204, 204));
        btConfirmar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btConfirmar.setForeground(new java.awt.Color(0, 204, 51));
        btConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SisBanco/L_Ok.jpg"))); // NOI18N
        btConfirmar.setMnemonic('C');
        btConfirmar.setText("Confirmar");
        btConfirmar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btConfirmarMouseExited(evt);
            }
        });
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });
        btConfirmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btConfirmarKeyReleased(evt);
            }
        });

        btLimpar.setBackground(new java.awt.Color(204, 204, 204));
        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btLimpar.setForeground(new java.awt.Color(255, 51, 51));
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SisBanco/L_Limpar.png"))); // NOI18N
        btLimpar.setMnemonic('L');
        btLimpar.setText("Limpar");
        btLimpar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btLimpar.setPreferredSize(new java.awt.Dimension(93, 33));
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlAgenciaSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ftContaSaque)
                                .addComponent(ftAgenciaSaque)
                                .addComponent(jlContaSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlValorSaque, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                            .addComponent(jlSenhaSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftValorSaque, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pfSenhaSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jlSenhaSaque)
                .addGap(0, 0, 0)
                .addComponent(ftAgenciaSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlAgenciaSaque)
                .addGap(0, 0, 0)
                .addComponent(ftContaSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlContaSaque)
                .addGap(0, 0, 0)
                .addComponent(ftValorSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlValorSaque)
                .addGap(0, 0, 0)
                .addComponent(pfSenhaSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConfirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btConfirmarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btConfirmarMouseExited

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        if(evt.getSource() == btConfirmar)
            realizarSaque();
            this.dispose();            
    }//GEN-LAST:event_btConfirmarActionPerformed

    private void btConfirmarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btConfirmarKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            realizarSaque();
            this.dispose();
        }
    }//GEN-LAST:event_btConfirmarKeyReleased

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        if(evt.getSource() == btLimpar)
            limparCampos();
    }//GEN-LAST:event_btLimparActionPerformed

    private void ftContaSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftContaSaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftContaSaqueActionPerformed

    private void pfSenhaSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfSenhaSaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfSenhaSaqueActionPerformed

    private void ftAgenciaSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftAgenciaSaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftAgenciaSaqueActionPerformed

    private void ftValorSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftValorSaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftValorSaqueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConfirmar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JFormattedTextField ftAgenciaSaque;
    private javax.swing.JFormattedTextField ftContaSaque;
    private javax.swing.JFormattedTextField ftValorSaque;
    private javax.swing.JLabel jlAgenciaSaque;
    private javax.swing.JLabel jlContaSaque;
    private javax.swing.JLabel jlSenhaSaque;
    private javax.swing.JLabel jlValorSaque;
    private javax.swing.JPasswordField pfSenhaSaque;
    // End of variables declaration//GEN-END:variables
}
