/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.SisBanco.view;

/**
 *
 * @author Vinicius
 */
public class IFSobre extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFSobre
     */
    public IFSobre() {
        initComponents();        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlLogoSisBanco = new javax.swing.JLabel();
        jlSisBanco = new javax.swing.JLabel();
        jlAutor = new javax.swing.JLabel();
        jlVersao = new javax.swing.JLabel();
        btFechar = new javax.swing.JButton();

        setTitle("Sobre o SisBanco");

        jlLogoSisBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SisBanco/L_SisBanco.jpg"))); // NOI18N

        jlSisBanco.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jlSisBanco.setForeground(new java.awt.Color(0, 0, 255));
        jlSisBanco.setText("SisBanco");

        jlAutor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlAutor.setForeground(new java.awt.Color(0, 0, 255));
        jlAutor.setText("Autor: Vinícius Albuquerque");

        jlVersao.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlVersao.setForeground(new java.awt.Color(0, 0, 255));
        jlVersao.setText("Versão: 1.0 - 2018");

        btFechar.setBackground(new java.awt.Color(51, 153, 255));
        btFechar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btFechar.setForeground(new java.awt.Color(255, 255, 0));
        btFechar.setText("Fechar");
        btFechar.setToolTipText("");
        btFechar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jlLogoSisBanco)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jlAutor))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jlVersao)
                                        .addGap(56, 56, 56))
                                    .addComponent(btFechar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jlSisBanco)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jlSisBanco)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlAutor)
                        .addGap(18, 18, 18)
                        .addComponent(jlVersao)
                        .addGap(45, 45, 45)
                        .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlLogoSisBanco))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btFecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFechar;
    private javax.swing.JLabel jlAutor;
    private javax.swing.JLabel jlLogoSisBanco;
    private javax.swing.JLabel jlSisBanco;
    private javax.swing.JLabel jlVersao;
    // End of variables declaration//GEN-END:variables
}
