/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.SisBanco.view;

import br.com.SisBanco.beans.Conta;
import br.com.SisBanco.beans.ContaCorrente;
import br.com.SisBanco.dao.ContaDAO;
import java.text.ParseException;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Vinicius
 */
public class IFTransferencia extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFTransferencia
     */
    public IFTransferencia() {
        initComponents();
    }
    
    protected void realizarTransferencia(){
        try {
        Conta c = new ContaCorrente();                  
        c.setNumeroConta(ftContaTransferencia.getText());  
        c.setNumeroAgencia(ftAgenciaTransferencia.getText()); 
        c.setTransferencia(Double.parseDouble(ftValorTransferencia.getText().replaceAll("\\,", ".")));
        String senha = new String(pfSenhaTransferencia.getPassword()).trim();                
        c.setSenha(senha);
        c.setAgenciaDestino(ftAgenciaDestino.getText());
        c.setContaDestino(ftContaDestino.getText());
        
            new ContaDAO().transferir(c);           
        } catch (Exception ex) {
            showMessageDialog(this, "Erro ao efetuar transferência!" + ex.getMessage(),"Erro",ERROR_MESSAGE);
        }                
    }
    
    protected void limparCampos(){
        ftAgenciaTransferencia.setText("");
        ftContaTransferencia.setText("");
        pfSenhaTransferencia.setText("");
        ftValorTransferencia.setText("");
        ftAgenciaTransferencia.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlAgenciaTransferencia = new javax.swing.JLabel();
        try {
            MaskFormatter fmtNumero = new MaskFormatter("####-#");
            fmtNumero.setPlaceholderCharacter('_');
            ftAgenciaTransferencia = new javax.swing.JFormattedTextField(fmtNumero);
            jlContaTransferencia = new javax.swing.JLabel();
            try{
                MaskFormatter fmtConta = new MaskFormatter("#####-##");
                fmtConta.setPlaceholderCharacter('_');
                ftContaTransferencia = new javax.swing.JFormattedTextField(fmtConta);
                jlValorTransferencia = new javax.swing.JLabel();
                ftValorTransferencia = new javax.swing.JFormattedTextField(new Double(0));
                jlSenhaTransferencia = new javax.swing.JLabel();
                pfSenhaTransferencia = new javax.swing.JPasswordField();
                jlAgenciaDestino = new javax.swing.JLabel();
                try {
                    MaskFormatter fmtAgencia = new MaskFormatter("####-#");
                    fmtAgencia.setPlaceholderCharacter('_');
                    ftAgenciaDestino = new javax.swing.JFormattedTextField(fmtAgencia);
                    jlContaDestino = new javax.swing.JLabel();
                    try{
                        MaskFormatter fmtContaDestino = new MaskFormatter("#####-##");
                        fmtContaDestino.setPlaceholderCharacter('_');
                        ftContaDestino = new javax.swing.JFormattedTextField(fmtContaDestino);
                        btConfirmar = new javax.swing.JButton();
                        btLimpar = new javax.swing.JButton();

                        setBackground(new java.awt.Color(51, 204, 255));
                        setClosable(true);
                        setIconifiable(true);
                        setMaximizable(true);
                        setTitle("Transferência");
                        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                        setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

                        jlAgenciaTransferencia.setText(" Conta:");

                    }catch(ParseException pe){}
                    ftAgenciaTransferencia.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ftAgenciaTransferenciaActionPerformed(evt);
                        }
                    });

                    jlContaTransferencia.setText(" Valor:");

                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null, "O erro é na conta para depósito", "Erro", 0);
                }
                ftContaTransferencia.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        ftContaTransferenciaActionPerformed(evt);
                    }
                });

                jlValorTransferencia.setText(" Senha:");

                ftValorTransferencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
                ftValorTransferencia.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        ftValorTransferenciaActionPerformed(evt);
                    }
                });

                jlSenhaTransferencia.setText(" Agência:");

                pfSenhaTransferencia.setEchoChar('*');
                pfSenhaTransferencia.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        pfSenhaTransferenciaActionPerformed(evt);
                    }
                });

                jlAgenciaDestino.setText(" Agência Destino:");
                jlAgenciaDestino.setMaximumSize(new java.awt.Dimension(36, 14));
                jlAgenciaDestino.setMinimumSize(new java.awt.Dimension(36, 14));
                jlAgenciaDestino.setPreferredSize(new java.awt.Dimension(36, 14));

            }catch(ParseException pe){}
            ftAgenciaDestino.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ftAgenciaDestinoActionPerformed(evt);
                }
            });

            jlContaDestino.setText("  Conta Destino:");

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "O erro é na conta para depósito", "Erro", 0);
        }
        ftContaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftContaDestinoActionPerformed(evt);
            }
        });

        btConfirmar.setBackground(new java.awt.Color(204, 204, 204));
        btConfirmar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btConfirmar.setForeground(new java.awt.Color(0, 204, 51));
        btConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SisBanco/L_Ok.jpg"))); // NOI18N
        btConfirmar.setMnemonic('C');
        btConfirmar.setText("Confirmar");
        btConfirmar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btConfirmarMouseExited(evt);
            }
        });
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });
        btConfirmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btConfirmarKeyReleased(evt);
            }
        });

        btLimpar.setBackground(new java.awt.Color(204, 204, 204));
        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btLimpar.setForeground(new java.awt.Color(255, 51, 51));
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SisBanco/L_Limpar.png"))); // NOI18N
        btLimpar.setMnemonic('L');
        btLimpar.setText("Limpar");
        btLimpar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btLimpar.setPreferredSize(new java.awt.Dimension(93, 33));
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(ftAgenciaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftContaDestino))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(btConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jlAgenciaTransferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(jlSenhaTransferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(ftAgenciaTransferencia)
                                    .addComponent(ftContaTransferencia))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlContaTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ftValorTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlValorTransferencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(pfSenhaTransferencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jlAgenciaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlContaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSenhaTransferencia)
                    .addComponent(jlContaTransferencia))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftAgenciaTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftValorTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAgenciaTransferencia)
                    .addComponent(jlValorTransferencia))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftContaTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfSenhaTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAgenciaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlContaDestino))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftAgenciaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftContaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ftAgenciaTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftAgenciaTransferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftAgenciaTransferenciaActionPerformed

    private void ftContaTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftContaTransferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftContaTransferenciaActionPerformed

    private void ftValorTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftValorTransferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftValorTransferenciaActionPerformed

    private void pfSenhaTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfSenhaTransferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfSenhaTransferenciaActionPerformed

    private void btConfirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btConfirmarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btConfirmarMouseExited

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        if(evt.getSource() == btConfirmar)
            realizarTransferencia();
            this.dispose();
    }//GEN-LAST:event_btConfirmarActionPerformed

    private void btConfirmarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btConfirmarKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            realizarTransferencia();
            this.dispose();
        }
    }//GEN-LAST:event_btConfirmarKeyReleased

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        if(evt.getSource() == btLimpar)
             limparCampos();
    }//GEN-LAST:event_btLimparActionPerformed

    private void ftAgenciaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftAgenciaDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftAgenciaDestinoActionPerformed

    private void ftContaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftContaDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftContaDestinoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConfirmar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JFormattedTextField ftAgenciaDestino;
    private javax.swing.JFormattedTextField ftAgenciaTransferencia;
    private javax.swing.JFormattedTextField ftContaDestino;
    private javax.swing.JFormattedTextField ftContaTransferencia;
    private javax.swing.JFormattedTextField ftValorTransferencia;
    private javax.swing.JLabel jlAgenciaDestino;
    private javax.swing.JLabel jlAgenciaTransferencia;
    private javax.swing.JLabel jlContaDestino;
    private javax.swing.JLabel jlContaTransferencia;
    private javax.swing.JLabel jlSenhaTransferencia;
    private javax.swing.JLabel jlValorTransferencia;
    private javax.swing.JPasswordField pfSenhaTransferencia;
    // End of variables declaration//GEN-END:variables
}
