/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.SisBanco.view;

import br.com.SisBanco.accessories.DesktopImagem;
import br.com.SisBanco.exe.JDSobre;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.net.URL;
import javax.swing.JFrame;

/**
 *
 * @author Vinicius
 */
public class JFPrincipal extends JFrame implements MouseListener{
    private DesktopImagem desktop;
    /**
     * Creates new form JFPrincipal
     */
    public JFPrincipal() {
        initComponents();         
      
        desktop = new DesktopImagem("L_Ifpb.jpg");
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(desktop,BorderLayout.CENTER);        
        getContentPane().add(tbNorte,BorderLayout.NORTH);
        pack();
                      
        URL url = getClass().getResource("L_Ifpb.jpg");
        Image im = Toolkit.getDefaultToolkit().getImage(url);
        setIconImage(im);
        
        Toolkit kit = Toolkit.getDefaultToolkit();  
        Dimension dm = kit.getScreenSize();
        int larg = dm.width;         
        int alt = dm.height;        
        setSize(larg, alt);      
    }   
    
    private void cadastrarClientes(){
        IFCliente janela = new IFCliente();
        janela.setLocation(330,30);
        desktop.add(janela);
        janela.setVisible(true);
    }
    
    private void cadastrarAgencias(){
        IFAgencia janela = new IFAgencia();
        janela.setLocation(330, 30);
        desktop.add(janela);
        janela.setVisible(true);
    }
    
    private void cadastrarContas(){
        IFConta janela = new IFConta();
        janela.setLocation(330,30);
        desktop.add(janela);
        janela.setVisible(true);
    } 

    private void depositar(){
        IFDeposito janela = new IFDeposito();
        janela.setLocation(450,120);
        desktop.add(janela);
        janela.setVisible(true);
    }
    
     private void sacar(){
        IFSaque janela = new IFSaque();
        janela.setLocation(450,50);
        desktop.add(janela);
        janela.setVisible(true);
    }
     
     private void transferir(){
        IFTransferencia janela = new IFTransferencia();
        janela.setLocation(450,50);
        desktop.add(janela);
        janela.setVisible(true);
    } 
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgBarraFerramentas = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        tbNorte = new javax.swing.JToolBar();
        btAgencias = new javax.swing.JButton();
        btClientes = new javax.swing.JButton();
        btContas = new javax.swing.JButton();
        btDeposito = new javax.swing.JButton();
        btSaque = new javax.swing.JButton();
        btTransferencia = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        mbBarra = new javax.swing.JMenuBar();
        meCadastros = new javax.swing.JMenu();
        miAgencias = new javax.swing.JMenuItem();
        miClientes = new javax.swing.JMenuItem();
        miContas = new javax.swing.JMenuItem();
        meMovimento = new javax.swing.JMenu();
        miDeposito = new javax.swing.JMenuItem();
        miSaque = new javax.swing.JMenuItem();
        miTransferencia = new javax.swing.JMenuItem();
        meManutencao = new javax.swing.JMenu();
        miSobre = new javax.swing.JMenuItem();
        miSair = new javax.swing.JMenuItem();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SisBanco");
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tbNorte.setRollover(true);
        tbNorte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbNorte.setFocusCycleRoot(true);

        btAgencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SisBanco/L_Agencia.jpg"))); // NOI18N
        btAgencias.setToolTipText("Cadastro de Agências");
        btAgencias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bgBarraFerramentas.add(btAgencias);
        btAgencias.setFocusable(false);
        btAgencias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAgencias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btAgencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgenciasActionPerformed(evt);
            }
        });
        btAgencias.addMouseListener(this);
        tbNorte.add(btAgencias);

        btClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SisBanco/L_Cliente.png"))); // NOI18N
        btClientes.setToolTipText("Cadastro de Clientes");
        bgBarraFerramentas.add(btClientes);
        btClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btClientes.setFocusable(false);
        btClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClientesActionPerformed(evt);
            }
        });
        btClientes.addMouseListener(this);
        tbNorte.add(btClientes);

        btContas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SisBanco/L_Conta.gif"))); // NOI18N
        btContas.setToolTipText("Cadastro de Contas");
        btContas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bgBarraFerramentas.add(btContas);
        btContas.setFocusable(false);
        btContas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btContas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContasActionPerformed(evt);
            }
        });
        btContas.addMouseListener(this);
        tbNorte.add(btContas);

        btDeposito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SisBanco/L_Deposito.jpg"))); // NOI18N
        btDeposito.setToolTipText("Depósito");
        btDeposito.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bgBarraFerramentas.add(btDeposito);
        btDeposito.setFocusable(false);
        btDeposito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btDeposito.setPreferredSize(new java.awt.Dimension(167, 161));
        btDeposito.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDepositoActionPerformed(evt);
            }
        });
        btDeposito.addMouseListener(this);
        tbNorte.add(btDeposito);

        btSaque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SisBanco/L_Saque.jpg"))); // NOI18N
        btSaque.setToolTipText("Saque");
        btSaque.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bgBarraFerramentas.add(btSaque);
        btSaque.setFocusable(false);
        btSaque.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSaque.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaqueActionPerformed(evt);
            }
        });
        btSaque.addMouseListener(this);
        tbNorte.add(btSaque);

        btTransferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SisBanco/L_Transferencia.jpg"))); // NOI18N
        btTransferencia.setToolTipText("Transferência");
        btTransferencia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bgBarraFerramentas.add(btTransferencia);
        btTransferencia.setFocusable(false);
        btTransferencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btTransferencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTransferenciaActionPerformed(evt);
            }
        });
        btTransferencia.addMouseListener(this);
        tbNorte.add(btTransferencia);

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SisBanco/L_Sair.png"))); // NOI18N
        btSair.setToolTipText("Sair");
        bgBarraFerramentas.add(btSair);
        btSair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSair.setFocusable(false);
        btSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        btSair.addMouseListener(this);
        tbNorte.add(btSair);

        meCadastros.setMnemonic('C');
        meCadastros.setText("Cadastro");
        meCadastros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        miAgencias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        miAgencias.setText("Agências");
        miAgencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miAgencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAgenciasActionPerformed(evt);
            }
        });
        meCadastros.add(miAgencias);

        miClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        miClientes.setText("Clientes");
        miClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClientesActionPerformed(evt);
            }
        });
        meCadastros.add(miClientes);

        miContas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        miContas.setText("Contas");
        miContas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miContasActionPerformed(evt);
            }
        });
        meCadastros.add(miContas);

        mbBarra.add(meCadastros);

        meMovimento.setMnemonic('M');
        meMovimento.setText("Movimentação");

        miDeposito.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        miDeposito.setText("Depósito");
        miDeposito.setToolTipText("");
        miDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDepositoActionPerformed(evt);
            }
        });
        meMovimento.add(miDeposito);
        miDeposito.getAccessibleContext().setAccessibleParent(meMovimento);

        miSaque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        miSaque.setText("Saque");
        miSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSaqueActionPerformed(evt);
            }
        });
        meMovimento.add(miSaque);
        miSaque.getAccessibleContext().setAccessibleParent(meMovimento);

        miTransferencia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        miTransferencia.setText("Transferência");
        miTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTransferenciaActionPerformed(evt);
            }
        });
        meMovimento.add(miTransferencia);
        miTransferencia.getAccessibleContext().setAccessibleParent(meMovimento);

        mbBarra.add(meMovimento);

        meManutencao.setMnemonic('A');
        meManutencao.setText("Manutenção");
        meManutencao.setToolTipText("");

        miSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        miSobre.setText("Sobre");
        miSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSobreActionPerformed(evt);
            }
        });
        meManutencao.add(miSobre);

        miSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        miSair.setText("Sair");
        miSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSairActionPerformed(evt);
            }
        });
        miSair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                miSairKeyReleased(evt);
            }
        });
        meManutencao.add(miSair);

        mbBarra.add(meManutencao);

        setJMenuBar(mbBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tbNorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbNorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(411, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClientesActionPerformed
        if(evt.getSource() == miClientes)
            cadastrarClientes();
    }//GEN-LAST:event_miClientesActionPerformed

    private void miContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miContasActionPerformed
        if(evt.getSource() == miContas)
            cadastrarContas();
    }//GEN-LAST:event_miContasActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        if(evt.getSource() == btSair)
            System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void btClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClientesActionPerformed
         if(evt.getSource() == btClientes)           
            cadastrarClientes();          
    }//GEN-LAST:event_btClientesActionPerformed

    private void btAgenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgenciasActionPerformed
        if(evt.getSource() == btAgencias)           
            cadastrarAgencias();           
    }//GEN-LAST:event_btAgenciasActionPerformed

    private void miAgenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAgenciasActionPerformed
        if(evt.getSource() == miAgencias)
            cadastrarAgencias();
    }//GEN-LAST:event_miAgenciasActionPerformed

    private void btContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContasActionPerformed
        if(evt.getSource() == btContas)          
            cadastrarContas();           
    }//GEN-LAST:event_btContasActionPerformed

    private void btDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDepositoActionPerformed
        if(evt.getSource() == btDeposito)
            depositar();
    }//GEN-LAST:event_btDepositoActionPerformed

    private void btSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaqueActionPerformed
        if(evt.getSource() == btSaque)
            sacar();
    }//GEN-LAST:event_btSaqueActionPerformed

    private void btTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTransferenciaActionPerformed
        if(evt.getSource() == btTransferencia)
            transferir();
    }//GEN-LAST:event_btTransferenciaActionPerformed

    private void miDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDepositoActionPerformed
        if(evt.getSource() == miDeposito)
            depositar();
    }//GEN-LAST:event_miDepositoActionPerformed

    private void miSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSaqueActionPerformed
        if(evt.getSource() == miSaque)
            sacar();
    }//GEN-LAST:event_miSaqueActionPerformed

    private void miTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTransferenciaActionPerformed
        if(evt.getSource() == miTransferencia)
            transferir();
    }//GEN-LAST:event_miTransferenciaActionPerformed

    private void miSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSobreActionPerformed
        if(evt.getSource() == miSobre){
            new JDSobre().setVisible(true);
        }
    }//GEN-LAST:event_miSobreActionPerformed
    private void miSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSairActionPerformed
       if(evt.getSource() == miSair)
           System.exit(0);
    }//GEN-LAST:event_miSairActionPerformed

    private void miSairKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_miSairKeyReleased
        if(evt.getKeyCode() == 27)
            System.exit(0);
    }//GEN-LAST:event_miSairKeyReleased

     
    public void mouseClicked(MouseEvent evt) {
        Object obj = evt.getSource();
        if(obj == btClientes)
            btClientes.setBackground(Color.RED);
        else if(obj == btAgencias)
            btAgencias.setBackground(Color.RED);
        else if(obj == btContas)
            btContas.setBackground(Color.RED);
        else if(obj == btDeposito)
            btDeposito.setBackground(Color.RED);
        else if(obj == btSaque)
            btSaque.setBackground(Color.RED);
        else if(obj == btTransferencia)
            btTransferencia.setBackground(Color.RED);
    }
    
    public void mouseExited(java.awt.event.MouseEvent evt){
        Object obj = evt.getSource();
        if(obj == btClientes)
            btClientes.setBackground(Color.WHITE);
        else if(obj == btAgencias)
            btAgencias.setBackground(Color.WHITE);
        else if(obj == btContas)
            btContas.setBackground(Color.WHITE);  
        else if(obj == btDeposito)
            btDeposito.setBackground(Color.WHITE);
        else if(obj == btSaque)
            btSaque.setBackground(Color.WHITE);
        else if(obj == btTransferencia)
            btTransferencia.setBackground(Color.WHITE);
    }
    
    public void mousePressed(java.awt.event.MouseEvent evt){}
    public void mouseReleased(java.awt.event.MouseEvent evt){}    
    public void mouseEntered(java.awt.event.MouseEvent evt){}
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgBarraFerramentas;
    private javax.swing.JButton btAgencias;
    private javax.swing.JButton btClientes;
    private javax.swing.JButton btContas;
    private javax.swing.JButton btDeposito;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSaque;
    private javax.swing.JButton btTransferencia;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JMenuBar mbBarra;
    private javax.swing.JMenu meCadastros;
    private javax.swing.JMenu meManutencao;
    private javax.swing.JMenu meMovimento;
    private javax.swing.JMenuItem miAgencias;
    private javax.swing.JMenuItem miClientes;
    private javax.swing.JMenuItem miContas;
    private javax.swing.JMenuItem miDeposito;
    private javax.swing.JMenuItem miSair;
    private javax.swing.JMenuItem miSaque;
    private javax.swing.JMenuItem miSobre;
    private javax.swing.JMenuItem miTransferencia;
    private javax.swing.JToolBar tbNorte;
    // End of variables declaration//GEN-END:variables

    private Object JDSobre() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
  
}
