/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  vinic
 * Created: 18/02/2018
 */

DROP DATABASE IF EXISTS SisBanco;

CREATE DATABASE SisBanco;

USE SisBanco;

CREATE TABLE AGENCIA(
    NUMERO_AGENCIA VARCHAR(6) NOT NULL PRIMARY KEY,
    NOME VARCHAR(40) NOT NULL
);

CREATE TABLE CLIENTE(
    CPF VARCHAR(11) NOT NULL PRIMARY KEY,
    NOME VARCHAR(40) NOT NULL,
    ID_AGENCIA VARCHAR(6) NOT NULL    
);

CREATE TABLE CONTA(
    NUMERO_CONTA VARCHAR(8) NOT NULL PRIMARY KEY, 
    NUM_AGENCIA VARCHAR(6) NOT NULL,
    ID_CPF VARCHAR(11) NOT NULL,
    TIPO_CONTA CHAR(2) NOT NULL,
    SALDO NUMERIC(15,2) NOT NULL,
    SENHA VARCHAR(15) NOT NULL,
    CHEQUE_ESPECIAL NUMERIC(15,2) NULL,
    VARIACAO NUMERIC(4,2) NULL
);

CREATE TABLE USUARIO(
    LOGIN VARCHAR(40) NOT NULL,
    SENHA VARCHAR(8) NOT NULL PRIMARY KEY
);

ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_AGENCIA
    FOREIGN KEY (ID_AGENCIA) REFERENCES AGENCIA (NUMERO_AGENCIA)
    ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CONTA ADD CONSTRAINT FK_CONTA_AGENCIA
    FOREIGN KEY (NUM_AGENCIA) REFERENCES AGENCIA (NUMERO_AGENCIA)
    ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CONTA ADD CONSTRAINT FK_CONTA_CLIENTE
    FOREIGN KEY (ID_CPF) REFERENCES CLIENTE (CPF)
    ON DELETE RESTRICT ON UPDATE RESTRICT;


