/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.SisBanco.exe;

/**
 *
 * @author Vinicius
 */
public class JDSobre extends javax.swing.JDialog {

    private String Sobre;

    /**
     * Creates new form JDSisBanco
     */
    public JDSobre(java.awt.Frame parent, boolean modal) {
        super(parent, modal);        
    }

    public JDSobre(){
        this.setModal(true);
        this.setLocation(450,50);
        initComponents();
    }    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlLogoSisBanco = new javax.swing.JLabel();
        jlSisBanco = new javax.swing.JLabel();
        jlAutor = new javax.swing.JLabel();
        jlVersao = new javax.swing.JLabel();
        btFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sobre o SisBanco");
        setName(Sobre);

        jlLogoSisBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SisBanco/L_SisBanco.jpg"))); // NOI18N
        jlLogoSisBanco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlSisBanco.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jlSisBanco.setForeground(new java.awt.Color(0, 0, 255));
        jlSisBanco.setText("SisBanco");
        jlSisBanco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlAutor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlAutor.setForeground(new java.awt.Color(0, 0, 255));
        jlAutor.setText("Autor: Vinícius Albuquerque");
        jlAutor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlVersao.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlVersao.setForeground(new java.awt.Color(0, 0, 255));
        jlVersao.setText("Versão: 1.0 - 2018");
        jlVersao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btFechar.setBackground(new java.awt.Color(51, 153, 255));
        btFechar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btFechar.setForeground(new java.awt.Color(255, 255, 0));
        btFechar.setText("Fechar");
        btFechar.setToolTipText("");
        btFechar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jlLogoSisBanco)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jlAutor))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jlVersao)
                                        .addGap(56, 56, 56))
                                    .addComponent(btFechar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jlSisBanco)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jlSisBanco)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlAutor)
                        .addGap(18, 18, 18)
                        .addComponent(jlVersao)
                        .addGap(45, 45, 45)
                        .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlLogoSisBanco))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDSobre dialog = new JDSobre(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });                
                //dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFechar;
    private javax.swing.JLabel jlAutor;
    private javax.swing.JLabel jlLogoSisBanco;
    private javax.swing.JLabel jlSisBanco;
    private javax.swing.JLabel jlVersao;
    // End of variables declaration//GEN-END:variables
}
